version: '3.1'
services:

  mom-remembers-main:
    build: ./main-server
    image: mom-remembers-main
    container_name: mom-remembers-main
    ports:
      - "8080:8080"
    depends_on:
      - mom-remembers-db
      - redis
    environment:
      - DB_NAME=mom-remembers
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - DB_HOST=mom-remembers-db
      - DB_PORT=5432
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  mom-remembers-db:
    image: postgres:14-alpine
    container_name: mom-remembers-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mom-remembers
      - DB_HOST=mom-remembers-db
      - DB_PORT=5432

  redis:
    image: "redis"
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  auth:
    build: ./auth-server
    container_name: auth
    depends_on:
      - auth-db
    ports:
      - "8081:8081"
    environment:
      - DB_NAME=authDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=auth-db
      - DB_PORT=5432

  auth-db:
    image: postgres:14-alpine
    container_name: authDB
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=authDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=auth-db
      - DB_PORT=5432